engines:
  duplication:
    enabled: true
    config:
      languages:
        python:

  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
exclude_paths:
  - tests/**
  - docs/**
ratings:
  paths:
    - satella/**
checks:
  argument-count:
    config:
      threshold: 10
  method-complexity:
    config:
      threshold: 40
  method-count:
    config:
      threshold: 70
