language: python
stages:
  - name: test
  - name: deploy
    if: branch = master
cache: pip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - pip install -r requirements.txt
  - pip install coverage nose2 requests
jobs:
  include:
    - stage: test
      python: "3.5"
      script:
        - bash tests/test_os/test_hang_until_sig.sh
        - coverage run -m nose2 -v
      after_script:
        - coverage xml
        - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
    - stage: test
      python: "3.6"
      script:
        - bash tests/test_os/test_hang_until_sig.sh
        - coverage run -m nose2 -v
      after_script:
        - coverage xml
        - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
    - stage: test
      python: "3.7"
      script:
        - bash tests/test_os/test_hang_until_sig.sh
        - coverage run -m nose2 -v
      after_script:
        - coverage xml
        - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
    - stage: test
      python: "3.8"
      script:
        - bash tests/test_os/test_hang_until_sig.sh
        - coverage run -m nose2 -v
      after_script:
        - coverage xml
        - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
    - stage: test
      python: "pypy3.5"
      script:
        - bash tests/test_os/test_hang_until_sig.sh
        - coverage run -m nose2 -v
      after_script:
        - coverage xml
        - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
    - stage: deploy
      python: "3.8"
      script:
        - bash build.sh

