language: python
python:
 - "2.7"
 - "3.5"
 - "3.4"
 - "pypy"
cache: pip
install:
 - pip install -r requirements.txt
script:
 - bash tests/test_posix/test_hang_until_sig.sh
 - python setup.py nosetests
after_success:
- bash build.sh
notifications:
   slack: digicort:lbgdFcFmWmHtHKDEMI3FwQK5

