language: python
python:
 - "2.7"
 - "3.5"
 - "pypy"
cache: pip
install:
 - pip install coverage nose mock
 - pip install -r requirements.txt
 - python setup.py install
script:
 - nosetests --with-coverage
 - bash tests/test_posix/test_hang_until_sig.sh

